### PR TITLE
add support for SH1106 in SPI mode

### PR DESCRIPTION
**Pull request by piontec**
I accidentally bought SH1106, which can't be easily turned into I2C mode. This PR adds support for this screen working in SPI mode.

### CODE REVIEW

**Comment by tbaumann** [comment]
A lot of white space changes. If they were necessary I would separate them in a separate commit. But in this case they seem to all be mistakes.

**Comment by piontec** [comment]
> A lot of white space changes. If they were necessary I would separate them in a separate commit. But in this case they seem to all be mistakes.

Why by mistake? They are all trailing (end of line) white spaces, useless characters that make your source code formatting worse. If you want, I can move them to a separate PR, but I really see no point, as they are a simple cleanup of literally 10 LOC. Keeping trailing white spaces shows poor code formatting practices. 

It would be also nice to hear some feedback about the actual changes, not only about if useless white spaces should be removed in a separate PR or not.

**Comment by murmeltier08** [comment]
The PR need a new rebase to the new master. Will be this possible?

**Comment by kjyv** [comment]
@piontec You will need to rebase this to the current master branch if you want this to be merged. The whitespace changes are fine I'd say, they actually remove unnecessary whitespace.

**Comment by piontec** [comment]
> @piontec You will need to rebase this to the current master branch if you want this to be merged. The whitespace changes are fine I'd say, they actually remove unnecessary whitespace.

Rebased, it would be nice to get review and merge before it gets conflicted again :)

**Comment by kjyv** [comment]
Code looks good to me now - I can't merge though, sorry ;)

**Review by kjyv — APPROVED** [review]

**Pull request merged**
