### PR TITLE
Animated WaterEmpty Logo (configurable)

### PR DESCRIPTION
**Pull request by genkigenki**
Changed code so WaterEmpty-animation is configurable.
Rebase & code cleanup.
New configuration option can be used for other animations, e.g. brew-logo-animation.

### CODE REVIEW

**Comment by fiendie** [comment]
To be perfectly honest, animations are a can of worms I don't really want to open. This is a lot of code for a little visual gimmick.

**Comment by genkigenki** [comment]
> To be perfectly honest, animations are a can of worms I don't really want to open. This is a lot of code for a little visual gimmick.

The base code (displayAnimCounter, FEATURE_ANIMATIONS) is needed only once (about 50%). Follow-up animations are less code.
LoQue has shown interest. @LoQue90 ?
By the way, feature is off by default.

**Comment by LoQue90** [comment]
Yes I like it, but I will add this locally to my mashine.

**Comment by fiendie** [comment]
Ok, closing it then.

**Comment by genkigenki** [comment]
Hi, can you reconsider? The comments in Discord were positive, thats why i rebased the code since December... 
Porting effort is on me - hope you see that I am an active contributor.

**Pull request closed without merging**
