### PR TITLE
Add machine state to mqtt

### PR DESCRIPTION
**Pull request by Nilaik**

### CODE REVIEW

**Review by LoQue90 — APPROVED** [review]
runs fine, but some states don´t get published because there are no up long enough

**Comment by Nilaik** [comment]
Yes that is true. In the linked issue I mentioned an alternative but am not sure if this is the right place to do it:

> Sending the machine state could also be added to printMachineState but that felt kind of weird since this function only contains debug prints. We would also need to duplicate the MQTT check in printMachineState so it is only called when MQTT is configured and connected.

**Comment by LoQue90** [comment]
Taking it from the debug print sounds not like a good idea. 
Until now I don't know what the mashine states in mqtt are good for. But the pid states are all up long enough to publish. 

> Yes that is true. In the linked issue I mentioned an alternative but am not sure if this is the right place to do it:
> 
> > Sending the machine state could also be added to printMachineState but that felt kind of weird since this function only contains debug prints. We would also need to duplicate the MQTT check in printMachineState so it is only called when MQTT is configured and connected.

**Comment by Nilaik** [comment]
I think it might be useful for automation in Home Assistant. For example I have a lamp at my desk that starts flashing when the target temperature is reached + 15 minutes waiting time, because I regularly start the machine continue working and forget to make my Espresso 🙈

At the moment I created my own helper state on the home assistant site when the target temperature is reached. But it might be nice to switch to the actual state the machine can publish like kPidNormal. 

Also Emergency Stop and Sensor Error are states that would be interesting for me to have in Home Assistant.

**Pull request merged**
