### PR TITLE
Fix brew timer during coldstart

### LINKED ISSUE #366: Coldstart interrupted from shot
Starting a shot during coldstart interrupts the coldstart.
When shot is finished or aborted mashine is switching into normal pid mode, instead of going back to coldstart.
At this point setpoint isn´t reached.

### PR DESCRIPTION
**Pull request by kjyv**
Fixes #366 by not running brew detection while heating up

### CODE REVIEW

**Comment by LoQue90** [comment]
i allready reworked the steamswitch to be implemented like the brew switch.
Off/Switch/trigger
maybe you want to add this here
https://github.com/LoQue90/clevercoffee/tree/rework-steamswitch

**Comment by kjyv** [comment]
> i allready reworked the steamswitch to be implemented like the brew switch. Off/Switch/trigger maybe you want to add this here https://github.com/LoQue90/clevercoffee/tree/rework-steamswitch

Nice, why isn't it a PR or merged already? ;)

**Comment by LoQue90** [comment]
> > i allready reworked the steamswitch to be implemented like the brew switch. Off/Switch/trigger maybe you want to add this here https://github.com/LoQue90/clevercoffee/tree/rework-steamswitch
> 
> Nice, why isn't it a PR or merged already? ;)

did this while trying to bring the switch config to the website, but never finished it.
PR is on the way :)

**Comment by kjyv** [comment]
Ok, I merged your PR and this is based on your changes now. I didn't test it yet but should behave the same

**Comment by kjyv** [comment]
Ok, also tested it and still works well

**Review by fiendie — APPROVED** [review]

**Comment by LoQue90** [comment]
runs fine on my silvia

**Pull request merged**
