### PR TITLE
Alpha 3.0.0/Added ability to turn heating on and off with an hardware switch

### PR DESCRIPTION
**Pull request by judokan9**
This feature was tested on my Rancilio Silvia (both trigger and classic switch) and it works with my esp8266.
It currently only supports inputs with integrated or external pull-down resistors.

If you looking forward to merge this feature, I am willing to update the documentation.

### CODE REVIEW

**Comment by murmeltier08** [comment]
Könnten wir zu dem PR im Chat mal sprechen ;)

**Comment by judokan9** [comment]
Sehr gerne, ich bin dort unter dem gleichen Namen zu finden.
Schreib mich einfach via PN an.

**Comment by tml89** [comment]
Tested with latest version. 
After rebase it is working fine.

**Comment by murmeltier08** [comment]
I resolve the conflict, can you test again?

**Comment by tml89** [comment]
tested and works

**Comment by murmeltier08** [comment]
You have to make a new PR for the master branch!

**Comment by murmeltier08** [comment]
I create a new PR

**Pull request merged**
