### PR TITLE
Fixed the scale readout with timed brewmode selected

### PR DESCRIPTION
**Pull request by jsve-dev**
Fixed shottimerscale(); never getting called with appropriate settings enabled.

Ps. this is my first pull request. I have about -18 idea what im doing... Hope im helping 😀

### CODE REVIEW

**Comment by LoQue90** [comment]
I'm very sorry, but this pr is doing a lot of stuff, but nothing that will actually change something helpful. 
What do you want to achieve?

**Comment by LoQue90** [comment]
Okay if I look only at the total diff, it's okay.
But it should only be one commit.
This shottimer scale call should only be done for people which are using only the pid and the scale.
If you are using the scale and controlling the brew, the scale shottimer is called differently.

**Comment by fiendie** [comment]
> Okay if I look only at the total diff, it's okay. But it should only be one commit. This shottimer scale call should only be done for people which are using only the pid and the scale. If you are using the scale and controlling the brew, the scale shottimer is called differently.

I've been chatting with him about this yesterday. I'll help squash the commits :)

**Comment by jsve-dev** [comment]
Cleaned up the mess... Now it just the useful change.
Thanks @fiendie

**Comment by LoQue90** [comment]
Can you tell my why do you want that change?
What is your setup?

**Comment by jsve-dev** [comment]
In the case of full expansion with valve control and scale. But still brew by time with continuous readout of scale output.
Without calling shottimerscale() the scale turns off during a brew and the readout shows 0.0g.

I of course had not thought about the pid-only usecase, but changing the line to BREWCONTROL_TYPE <= 1 should cover both instances

**Comment by LoQue90** [comment]
Should be < 2 to not make weird stuff if someone uses brew by scale.

**Comment by jsve-dev** [comment]
Changed to <2

**Comment by LoQue90** [comment]
@FabianSperrle but you also have brewcontrol 2 set?
This one should fix the scale readout for onlypidscale.
If I'm correct.

**Review by LoQue90 — APPROVED** [review]

**Pull request merged**
