### PR TITLE
MAX31865 RTG temp sensor support

### PR DESCRIPTION
**Pull request by tbaumann**
This is so far work in progress and untested.

Referring to https://github.com/rancilio-pid/ranciliopid/issues/266

### CODE REVIEW

**Comment by tbaumann** [comment]
Works now. Please apologize for the mDNS commit. If you want to keep it clean I can take it out of this MR.

**Comment by murmeltier08** [comment]
I will test the PR soon.

**Comment by tbaumann** [comment]
Actually I have some cleanup. Give me a sec and I commit it

**Comment by kjyv** [comment]
Looks good but why the MDNS stuff?

**Comment by tbaumann** [comment]
> Looks good but why the MDNS stuff?

I just noticed that the hostname gets advertised (By OTA) but the webinterface doesn't. This adds a service record.
But honestly it has no real business to be in this pull request. I can take it out.

In fact I am thinking of re-writing the WLAN manager section. If I get around doing it. At the moment the code is blocking at boot until WLAN is connected and it never tries any reconnect, that's totally not necessary.
There are a few ways to switch between AP and online modus automatically...
I would throw the mDNS change in there once I get around doing it.
I might also try to port Gagguino to ESP32 instead...

**Comment by murmeltier08** [comment]
We change the wifi manager, after 30 seconds the offline mode starts or do you mean something else?

**Comment by kjyv** [comment]
I think mDNS might not be enabled automatically with ESP32? With ESP8266 it already works fine without explicitly adding it.
You mean at boot it would be nice if it started heating right away while also trying to connect to WiFi and retrying as well if not successful in parallel? Would be nice but also might be a bit tricky to do things in parallel?

**Comment by tbaumann** [comment]
> We change the wifi manager, after 30 seconds the offline mode starts or do you mean something else?

I just want to make it entirely dynamic and automatic. Looking at https://hieromon.github.io/AutoConnect/index.html but there are more lightweight options...
The web interface shouldn't really care how it's on-line (connected to a configured WiFi or in Captive portal mode on it's own AP) and when one of the configured WiFi networks come online it should just auto-connect there.

Right now it blocks while it tries and after timeout it goes offline

**Comment by tbaumann** [comment]
> I think mDNS might not be enabled automatically with ESP32? With ESP8266 it already works fine without explicitly adding it. You mean at boot it would be nice if it started heating right away while also trying to connect to WiFi and retrying as well if not successful in parallel? Would be nice but also might be a bit tricky to do things in parallel?

The A record is automatic the SRV record not. That's why I added it

**Comment by kjyv** [comment]
Aha, I see.
Anyway, the AP logic is intended to let you reconfigure you WiFi config in case it can't connect. The workflow you describe is not straight forward to use as it would mean you still see the normal website in AP mode (which could be a useful to have optional feature though in case there is no wifi to use the machine with) - how would you change wifi credentials in that case using the WifiManager UI? I guess we could have a reset button in the website somewhere

**Comment by tbaumann** [comment]
> Aha, I see. Anyway, the AP logic is intended to let you reconfigure you WiFi config in case it can't connect. The workflow you describe is not straight forward to use as it would mean you still see the normal website in AP mode (which could be a useful to have optional feature though in case there is no wifi to use the machine with) - how would you change wifi credentials in that case using the WifiManager UI? I guess we could have a reset button in the website somewhere

Perhaps not the best place to discuss here. But of course there would be a settings page to select the wifi.

And even if we don't set it up like this. There is absolutely no need to block the boot process. The wifi manager can give you a callback on fail and success.

**Comment by kjyv** [comment]
Not the best place since it is not related to the temp sensor true, but just one last remark: The blocking is not ideal true, but apart from not being connected, it should mainly not keep the machine from heating until the portal times out. The fact that it does not connect after a few retries and the set timeout is probably not improved by retrying to connect again and again. Ideally it should just connect every time.

**Comment by tbaumann** [comment]
> Not the best place since it is not related to the temp sensor true, but just one last remark: The blocking is not ideal true, but apart from not being connected, it should mainly not keep the machine from heating until the portal times out. The fact that it does not connect after a few retries and the set timeout is probably not improved by retrying to connect again and again. Ideally it should just connect every time.

I might be wrong, but I don't think it's running before it connects. At least that is when the debug output starts. (I don't have my display yet and only a bench setup.)

**Comment by kjyv** [comment]
I might have put that a bit weird. I meant that the code currently does not start heating before it is connected, but it ideally should because it delays the startup a lot if for some reason the connection is not possible. I think that is the main thing to fix in terms of WifiManager, otherwise I don't see a problem with the current logic.

**Comment by tbaumann** [comment]
> I try the PR and get a build error. Can you check your PR again, please? `src/rancilio-pid.cpp:788:1: error: expected declaration before '}' token` I find the wrong } and correct it, can you please check if everything works with the our sensor?

I will rebase it without mdns support (and without the syntax error you added :D )

**Comment by tbaumann** [comment]
Run it again. Works for me

**Comment by tbaumann** [comment]
Ah you found the bracket. :D 
I will try to give it a test tomorrow. But I'm quite sure it will be fine. That one merged commit is totally harmless.

**Comment by murmeltier08** [comment]
I have the problem that my machine stucks while booting now.

**Comment by LoQue90** [comment]
@tbaumann would you like to look over your PR?
rebase and stuff? so we could merge this
wich sensor do I need to test this?
Thanks!

**Comment by tbaumann** [comment]
Sorry for the late replay. Busy times.

I no longer use rancilio-pid on my machine. I don't have a need for this right now. If you merge it, you have to maintain it.
But it might be worth it. It's a much more reliable option to thermocouples. Physically and in terms of electrical interference.

I'm happy to rebase it for you. Give me a few days...

**Comment by fiendie** [comment]
Closing because PR is stale and doesn't work with the current pin mapping on our PCB.

**Pull request closed without merging**
